/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.resubmit;
import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;

public class App {

    public static void main(String[] args) {
        // Read file
        String path = "C:\\Users\\Rawzi Homran\\quotes-resubmit\\app\\src\\main\\java\\quotes\\resubmit\\recentquotes.json" ;
        String json = readJsonFile(path);

        Gson gson = new Gson();

        Quotes[] quotesArray = gson.fromJson(json, Quotes[].class);
        Random random = new Random();
        int size = quotesArray.length - 1 ;
        int number = random.nextInt(size + 1 );
        System.out.println(quotesArray[number]);
    }

    public static String readJsonFile(String path) {
        Path path1 = Paths.get(path);
        String json = "" ;
        try {
            BufferedReader reader = Files.newBufferedReader(path1);
            String str = reader.readLine();
            while(str != null){
                json += str + "\n" ;
                str = reader.readLine();
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        return json ;
    }
}
