/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes.resubmit;

import com.google.gson.Gson;
import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void quoteTest(){
        String json = App.readJsonFile("C:\\Users\\Rawzi Homran\\quotes-resubmit\\app\\src\\main\\java\\quotes\\resubmit\\recentquotes.json");
        Gson gson = new Gson();
        Quotes[] quotesArray = gson.fromJson(json, Quotes[].class);
        String expected = String.valueOf(quotesArray[0]);
        String actual = "Quotes{author='Marilyn Monroe', likes='18651 likes', text='I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.'}" ;
        assertEquals(expected , actual);
    }
}
